using Microsoft.AspNetCore.Mvc;

namespace V2RayWeb.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class V2RayNodesController : ControllerBase
    {
        private readonly ILogger<V2RayNodesController> _logger;
        public V2RayNodesController(ILogger<V2RayNodesController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetV2RayNodes")]
        public string Get()
        {
            return "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkphcGFuRWFzdEFnZW50IiwNCiAgImFkZCI6ICJqcGVhc3QuamFwYW5lYXN0LmNsb3VkYXBwLmF6dXJlLmNvbSIsDQogICJwb3J0IjogIjI4MzAyIiwNCiAgImlkIjogIjIzZGFkODJiLWNhNDQtNGVkZS1iYjlhLWFhNTFiMDFhOWUyYiIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogIm5vbmUiLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIiwNCiAgImZwIjogIiINCn0=\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIktvZXJhQ2VudHJhbCIsDQogICJhZGQiOiAia29lcmFjLmtvcmVhY2VudHJhbC5jbG91ZGFwcC5henVyZS5jb20iLA0KICAicG9ydCI6ICIyODMwMiIsDQogICJpZCI6ICI5NjVlY2FkNi1mMWUzLTQ4ODMtOGEwOS00YWFkNjhlYzZjYTkiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJub25lIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiIsDQogICJmcCI6ICIiDQp9\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIk5vcnRoVVMiLA0KICAiYWRkIjogIm5vcnRodXMubm9ydGhjZW50cmFsdXMuY2xvdWRhcHAuYXp1cmUuY29tIiwNCiAgInBvcnQiOiAiMjgzMDIiLA0KICAiaWQiOiAiMjFlYmVmNGYtMGNjNC00ZTIyLTg0YjMtNjdjZDJmNTA5NTk2IiwNCiAgImFpZCI6ICI2NCIsDQogICJzY3kiOiAibm9uZSIsDQogICJuZXQiOiAidGNwIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAiIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiLA0KICAiZnAiOiAiIg0KfQ==\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIlNvdXRoZWFzdEFzaWFBZ2VudCIsDQogICJhZGQiOiAic291dGhlYS5zb3V0aGVhc3Rhc2lhLmNsb3VkYXBwLmF6dXJlLmNvbSIsDQogICJwb3J0IjogIjI4MzAyIiwNCiAgImlkIjogIjUxNjE1ZGM3LWI1ZTctNDNiMC05NTQ3LWRhYzM5Yzk3NTRmNiIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogIm5vbmUiLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIiwNCiAgImZwIjogIiINCn0=\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIlNvdXRoIENlbnRyYWwgVVMiLA0KICAiYWRkIjogInNjdS5zb3V0aGNlbnRyYWx1cy5jbG91ZGFwcC5henVyZS5jb20iLA0KICAicG9ydCI6ICIyODMwMiIsDQogICJpZCI6ICI5OGQ1YzFiMi05YjcwLTRmYmItOThlZi1kNjBhZjA4ZGRiNGIiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJub25lIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0=\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkF1c3RyYWxpYUVhc3QiLA0KICAiYWRkIjogImF1dGh0cmFlYXN0LmF1c3RyYWxpYWVhc3QuY2xvdWRhcHAuYXp1cmUuY29tIiwNCiAgInBvcnQiOiAiMjgzMDIiLA0KICAiaWQiOiAiOTJlYmYwOTMtYzQzMy00Mjc0LWFmMGUtOTM0MDMzOGQxYWE0IiwNCiAgImFpZCI6ICI2NCIsDQogICJzY3kiOiAibm9uZSIsDQogICJuZXQiOiAidGNwIiwNCiAgInR5cGUiOiAibm9uZSIsDQogICJob3N0IjogIiIsDQogICJwYXRoIjogIiIsDQogICJ0bHMiOiAiIiwNCiAgInNuaSI6ICIiLA0KICAiYWxwbiI6ICIiDQp9\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkphcGFuRWFzdEJhY2t1cCIsDQogICJhZGQiOiAianB0ZXN0LmphcGFuZWFzdC5jbG91ZGFwcC5henVyZS5jb20iLA0KICAicG9ydCI6ICIxMjM0NSIsDQogICJpZCI6ICI3OGE1OTczNC1lZmQ0LTQ0ZTEtYTc4Yy0zNzQ5YmNlNjRlZGYiLA0KICAiYWlkIjogIjY0IiwNCiAgInNjeSI6ICJub25lIiwNCiAgIm5ldCI6ICJ0Y3AiLA0KICAidHlwZSI6ICJub25lIiwNCiAgImhvc3QiOiAiIiwNCiAgInBhdGgiOiAiIiwNCiAgInRscyI6ICIiLA0KICAic25pIjogIiIsDQogICJhbHBuIjogIiINCn0=\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkVhc3RBc2lhIiwNCiAgImFkZCI6ICJlYXN0YXNpYWhrLmVhc3Rhc2lhLmNsb3VkYXBwLmF6dXJlLmNvbSIsDQogICJwb3J0IjogIjI4MzAyIiwNCiAgImlkIjogIjQwZDg2ZWUyLWRkYTItNDliZi04N2U5LTU3MjczN2YzYzcxNSIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogIm5vbmUiLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ==\r\n" +
                    "vmess://ew0KICAidiI6ICIyIiwNCiAgInBzIjogIkVhc3RVUyIsDQogICJhZGQiOiAiZXN0dXMuZWFzdHVzLmNsb3VkYXBwLmF6dXJlLmNvbSIsDQogICJwb3J0IjogIjI4MzAyIiwNCiAgImlkIjogImMxMzU1N2RjLTk4NTMtNDk1OC1hNmNhLTNkYjFhMTlmNTFhNiIsDQogICJhaWQiOiAiNjQiLA0KICAic2N5IjogIm5vbmUiLA0KICAibmV0IjogInRjcCIsDQogICJ0eXBlIjogIm5vbmUiLA0KICAiaG9zdCI6ICIiLA0KICAicGF0aCI6ICIiLA0KICAidGxzIjogIiIsDQogICJzbmkiOiAiIiwNCiAgImFscG4iOiAiIg0KfQ==\r\n";
        }
    }
}
